@ECHO ON
py tf-test.py
timeout 3
py delete-old-file.py
timeout 3
py user-input.py
timeout 3
py bicubic.py
timeout 3
py predict-enhance.py
timeout 3
py predict-bicubic-enhance.py
timeout 3
py image-quality-assessment.py
timeout 3
py img-denoise.py
timeout 3
py img-bicubic-denoise.py
timeout 3
py user-output.py
timeout 3
py reinput-updown.py
timeout 3
py delete-old-file.py
timeout 3
py user-input.py
timeout 3
py bicubic2x-up.py
timeout 3
py predict-bicubic2x-enhance.py
timeout 3
py image-quality-assessment.py
timeout 3
py bicubic2x-down.py
timeout 3
py img-bicubic-denoise-downscaled.py
timeout 3
py user-output.py
timeout 10


